# Server configuration settings
server:
  host: "app" 
  port: 8080 
  shutdown_timeout: 30 # in second
  read_timeout: 5 # in second
  write_timeout: 10 # in second
  idle_timeout: 120 # in second
  debug: true 

# Database configuration
postgres:
  host: "postgres"
  port: 5432
  database: "my_db"
  user: "user"
  password: "password"
  ssl_mode: "disable"

# Kafka configuration
kafka:
  network: "tcp"
  brokers: ["broker:9092"]
  topic: "my-topic"
  group_id: "1"
  poll_timeout: 1000 # in milliseconds

# Cache configuration
cache:
  capacity: 1000 
  ttl: 24 # Cache entry time-to-live in hours (on debug mode) or seconds (on production mode)
